module dmd.types.TypeClass;

import dmd.Global;
import std.format;

import dmd.Type;
import dmd.scopeDsymbols.ClassDeclaration;
import dmd.types.TypeInstance;
import dmd.Dsymbol;
import dmd.Scope;
import dmd.HdrGenState;
import std.array;
import dmd.Expression;
import dmd.Identifier;
import dmd.varDeclarations.TypeInfoDeclaration;
import dmd.types.TypePointer;
import dmd.Declaration;
import dmd.VarDeclaration;
import dmd.Token;
import dmd.expressions.DotExp;
import dmd.expressions.ScopeExp;
import dmd.expressions.DotVarExp;
import dmd.expressions.VarExp;
import dmd.expressions.PtrExp;
import dmd.expressions.AddExp;
import dmd.expressions.IntegerExp;
import dmd.expressions.DotIdExp;
import dmd.dsymbols.EnumMember;
import dmd.scopeDsymbols.TemplateMixin;
import dmd.scopeDsymbols.TemplateDeclaration;
import dmd.scopeDsymbols.TemplateInstance;
import dmd.dsymbols.OverloadSet;
import dmd.expressions.DotTypeExp;
import dmd.expressions.TupleExp;
import dmd.varDeclarations.ClassInfoDeclaration;
import dmd.varDeclarations.TypeInfoInterfaceDeclaration;
import dmd.varDeclarations.TypeInfoClassDeclaration;
import dmd.expressions.NullExp;
import dmd.expressions.TypeExp;
import dmd.expressions.DotTemplateExp;
import dmd.expressions.ErrorExp;
import dmd.expressions.ThisExp;
import dmd.expressions.CommaExp;


import std.string : toStringz;

import dmd.DDMDExtensions;

class TypeClass : Type
{
	mixin insertMemberExtension!(typeof(this));

    ClassDeclaration sym;

    this(ClassDeclaration sym)
	{
		super(Tclass);
		this.sym = sym;
	}

    override ulong size(Loc loc)
	{
		return PTRSIZE;
	}
	
    override string toChars()
	{
		if (mod)
			return Type.toChars();
		return sym.toPrettyChars();
	}
	
    override Type syntaxCopy()
	{
		assert(false);
	}
	
	
	
    override void toDecoBuffer(ref Appender!(char[]) buf, int flag)
	{
		string name = sym.mangle();
		//printf("TypeClass.toDecoBuffer('%s' flag=%d mod=%x) = '%s'\n", toChars(), flag, mod, name);
		Type.toDecoBuffer(buf, flag);
		formattedWrite(buf,"%s", name);
	}
	
    override void toCBuffer2(ref Appender!(char[]) buf, ref HdrGenState hgs, MOD mod)
	{
		if (mod != this.mod)
		{	
			toCBuffer3(buf, hgs, mod);
			return;
		}
		buf.put(sym.toChars());
	}

	
    override ClassDeclaration isClassHandle()
	{
		return sym;
	}
	
    override bool isBaseOf(Type t, int* poffset)
    {
        assert (false);
    }	
	
	
	
	
    override bool isauto()
	{
		return sym.isauto;
	}
	
    override bool checkBoolean()
	{
		return true;
	}
	
    override TypeInfoDeclaration getTypeInfoDeclaration()
	{
		if (sym.isInterfaceDeclaration())
			return new TypeInfoInterfaceDeclaration(this);
		else
			return new TypeInfoClassDeclaration(this);
	}
	
	
    override bool builtinTypeInfo()
	{
		/* This is statically put out with the ClassInfo, so
		 * claim it is built in so it isn't regenerated by each module.
		 */
		return mod ? false : true;
	}
	

	
}
